### ISSUE TITLE
full path for unzip

### ISSUE THREAD

**Issue by gschrader** [osoco/puppet-grails#1]
Hi, I receive the following:

```
err: Failed to apply catalog: 'unzip grails-2.1.1.zip' is not qualified and no path was specified. Please qualify the command or specify a path.
```

I'm able to work around it by specifying the full path for unzip like this:

```
        command => "/usr/bin/unzip grails-$version.zip",
```

I'm a bit of a puppet newbie so I'm not sure if this is the correct way to resolve this or not.

**Comment by deltamualpha** [comment]
This is also resolved by my (languishing) pull request.
